### ISSUE TITLE
Firefox shows native scrollbar over custom one on Mac

### ISSUE THREAD

**Issue by gromo** [gromo/jquery.scrollbar#12]
Firefox shows native scrollbar over custom one on Mac. Issue was reported to Mozilla: https://bugzilla.mozilla.org/show_bug.cgi?id=926294

**Comment by jeekca** [comment]
@gromo "Set option ignoreOverlay to false."

Oh man, thank you for that. I just spent 3 hours trying to figure out what I was doing wrong. Worked in every browser on Windows, but not on MAC. I guess it should have clicked sooner, but I was too busy blaming my own code. Thank you. Love the plugin!

**Comment by mfwonghk** [comment]
I did some testing in OSX today, using 0.2.8. First, I commented row "|| (browser.macosx && !browser.webkit) // still required to ignore nonWebKit browsers on Mac" in the code.

Tested in:
OSX 10.9.5: Safari 7.1.7, Firefox 39.0 and Chrome 44.0
OSX 10.10.4, Safari 8.0.7, Firefox 39.0 and Chrome 44.0

and the plugin is working correctly, at least in <div>. I havn't test in textarea. No native scrollbar.

**Comment by gromo** [comment]
Safari and Chrome are OK for sure - they are webkit-based.
But Firefox may show native scrollbars - it depends on system settings. Can you check it again using different settings?

**Comment by mfwonghk** [comment]
After some more testing, I think this bug is related to Mac OS settings. In "System Preference > General > Show scroll bars",

If set to "Automatically based on mouse or trackpad", no native scrollbar if using mouse, has native scrollbar if using trackpad.
If set to "When Scrolling", has native scrollbar.
If set to "Always", then no native scrollbar.

For whatever cases, since most scrolling of my page depends on this plugin, I will comment row "|| (browser.macosx && !browser.webkit)" to enable it in Mac Firefox.

**Comment by devoizo** [comment]
Возможное решение предложил @clexit в Diokuz/baron#91
> A bit hacky way would be to add something like "margin-right: -30px; padding-right: 30px;" to a scrollable container and then cut these 30px by setting "overflow: hidden" to a wrapper, so the native scrollbars will be hidden.

**Comment by gromo** [comment]
Изначально именно так я и скрываю родные скроллбары - используя отрицательный margin на ширину/высоту скроллбара. Однако в Мак-е у всех браузеров ширина/высота скроллбара 0. Придётся делать какой-то хак специально для ФФ под маком + добавлять паддинг в контейнер, что может нарушить вёрстку, если в блоке уже использовался какой-то паддинг.
