### ISSUE TITLE
Question: Why should I set ignoreMobile = true (default)

### ISSUE THREAD

**Issue by julmot** [gromo/jquery.scrollbar#24]
My question is, why I have the option to disable the scrollbar initialization on mobile devices. Since I set "overflow:hidden;" on the scroll element to prevent the default scrollbar it would make no sense then to not show up the custom scrollbar. This would show nothing.

**Comment by gromo** [comment]
There are 2 types of custom scrollbar plugins:
1. Plugin that hides scrollbars with overflow:hidden and handle all scroll events - plugin should emulate/handle all scrolling events (by keyboard, mouse, trackball, touch, on focus, on text selection, etc...) and it actually is not possible
2. Plugin that hides native scrollbars with some sort of CSS and just listen container's scroll event to update custom scrollbar position - this way content is scrolled by browser itself and supports all scrolling types that browser supports + it's a way faster than handle scrolling events manually + less code

jQuery Scrollbar plugin uses second way - it uses native browser scrolling, but not all scrollbars are possible to hide with CSS (or, at least I cound find the way to hide scrollbar in FF on Mac). So your CSS value "overflow:hidden" is overwritten in scrollbar CSS to enable native browser scrolling, and in some cases you can see double scrollbar - native and custom ones. That's why option 'ignoreMobile' is set to true by default. Enabling custom scrollbar on mobile devices is on your own risk.

**Comment by julmot** [comment]
Well I understand your point of view. But since you said that even in option 2 the scrollbar will be not visible one question remains: how do you hide only the scrollbar? IMHO you could only do that with calculating the scrollbars with and than wrap the element where the scrollbar should appear in a element that has X more pixels (like the browser scrollbar width). Then it would not be visible and the events would still get fired. Is that the way the plugin works?

In which cases will I see double scrollbar? I want to prevent that.

**Comment by gromo** [comment]
@julmot 
> you could only do that with calculating the scrollbars with and than wrap the element where the scrollbar should appear in a element 

If you look at plugin source code you will find there function `getBrowserScrollSize` and, if you expect element in Firebug/Element inspector, you'll see that original element is wrapped into additional wrapper with class `scroll-wrapper`. 

> In which cases will I see double scrollbar?

It may happens in non-webkit browsers where native scrollbar is placed over content (mobile/MacOS browsers), so I can't calculate its size and can't hide it with CSS. For example, Firefox on Mac or some mobile browsers (I can't say which ones, as I didn't test plugin on mobile devices). But, fortunatelly, most of the browsers are webkit-based - Google Chrome, Chromium, new Opera, Safari
