### ISSUE TITLE
Solution for Firefox

### ISSUE THREAD

**Issue by sparrox** [gromo/jquery.scrollbar#42]
This script works fine except on Firefox (37.0.1) mac (Maverick but doesn't work on Yosemite too).

Is there any fix for that ?

**Comment by gromo** [comment]
Unfortunatelly FF on Mac is not supported at all because of issue with hiding native scrollbars

**Comment by mzysk** [comment]
hi @gromo - nice script and i developed it in my recent project. Could you tell me why you didn't expose that information about not supporting ff at all? 

There's no mention about that in supported browser section, also not mentioned in limitations and in your comparision table theres a pointed bug with showing native scrollbars. But there's no any information about not supporting it at all.

I expected to have working script with little bug, not to disable it entirely on ff mac. Could you point out what to do to trigger script in mac ff on my own?

Thanks in advance.

**Comment by gromo** [comment]
Hi @mzysk. You can comment row 223: `|| (browser.macosx && !browser.webkit) // still required to ignore nonWebKit browsers on Mac` in order to force showing custom scrollbar in Mac FF - but there is no way to hide native scrollbar except of `overflow:hidden`, but if I do so - I will have to handle all mouse/touch events in order to emulate scrolling - it won't be native browser's one.

**Comment by mzysk** [comment]
Hey @gromo - thank you. I've commented that line and it works good in Firefox Max 37.0.1 and 38.0.5
![screen 2015-06-17 o 10 41 35](https://cloud.githubusercontent.com/assets/12586719/8202835/bd3f8ea0-14dd-11e5-984b-3418950de65f.png)

Maybe Firefox change something on their side or my configuration is (luckily for me) just very simple.

Thank You for your help again!

**Comment by gromo** [comment]
@mzysk I believe it's your system settings, but I'm glad that it help you
