### ISSUE TITLE
Best way to use the scrollbar as body-scrollbar?

### ISSUE THREAD

**Issue by julmot** [gromo/jquery.scrollbar#48]
When using this plugin as a body-scrollbar in combination with parallax plugins the problem occurs that the `$(window).scroll()`-event doesn't get fired. Of course this is correct, because the only thing that fires the scroll-event is the scrollbar-div. However, this makes it impossible to use such plugins. Is there any workaround?

**Comment by gromo** [comment]
There are 2 ways to do this:
1. Use `position:fixed` for your scrollable div and update body height/width/scroll with your scrollable dimensions
2. Patch your parallax plugin to handle scroll of your div instead of body

I recommend to use second way as it's much easier. Unfortunately you have to make this patch every time you update your plugin to newer version.

**Comment by julmot** [comment]
Thank your for the reply. Could you please explain the first point? Do you mean I should set the body-height to the scrollable-height?

**Comment by gromo** [comment]
The main idea is that your body content is invisible, but scrollable - it's covered by your fixed element. And you update your body content's dimensions with your fixed element's content ones. It's really not good idea to do it that way, but it's possible as one of the ways to accomplish your goal.

I recommend you to look at  your parallax source code and if it uses jQuery-based `scroll` event, you can trigger `scroll` event for body from your custom div element. Something like
`$('.my-div').on('scroll', function(event){ $('body').trigger(event); })`
