### ISSUE TITLE
How to add space to the scrollbar on top and bottom?

### ISSUE THREAD

**Issue by julmot** [gromo/jquery.scrollbar#62]
I tried using padding on `.scroll-bar` and `.scroll-element_track`. Nothing worked for me. I just want to add 2px space on top and bottom of the scrollbar so that it is not totally on the edge.

**Comment by gromo** [comment]
padding won't work - you have to update CSS styles for scrollbar you need, because every scrollbar uses different styles.

So, to add padding 2px to your scrollbar, update next CSS:
for `scroll-element_outer` add 2px to `top` value or create one
for `scroll-element_size` and `scroll-element_track` subtract -4px from current value (2px of top + 2px from bottom)

**Comment by julmot** [comment]
> for scroll-element_size and scroll-element_track subtract -4px from current value (2px of top + 2px from bottom)
Do you mean with JS? If not, could you explain how?

**Comment by julmot** [comment]
:8ball:

**Comment by gromo** [comment]
@julmot 

Sorry, I was so busy that forgot about your question. To add space, just update jquery.scrollbar.css for your scrollbar as I wrote before. No need in JS

**Comment by julmot** [comment]
Well I already tried this. Could you explain this in more detail?

**Comment by gromo** [comment]
Look at scrollbar-light example [here](http://jsfiddle.net/pyssvrjc/2/).

I've added top/bottom space only to vertical scrollbar. If you need horizontal one, add it yourself + don't forget to add extra space for vertical/horizontal scrollbars if they are both visible.
