### ISSUE TITLE
Scrollbar plugin calculates wrong max height 

### ISSUE THREAD

**Issue by stephanlenhart** [gromo/jquery.scrollbar#76]
I'm using the jQuery Scrollbar plugin in 3 parallel DIV columns. The height of the columns always adapt to the height of the browser window. For some reason, the scrollbar height in the **2nd column** is not calculated correctly. After some days of debugging I found out that one child DIV inside the 2nd column seems to trigger this issue. 

It's the "item_cnt" DIV. Whenever setting this DIV to display:none, everything works fine. Unfortunately I need this DIV and cannot find a workaround how to make the scrollbar run with it.

I've created a **[fiddle](https://jsfiddle.net/deb_ugger/8a10grcz/)**.

**Comment by gromo** [comment]
You are doing wrong several things:
1. Set height to inner DIV instead of scrollable one
2. Set height via JS - use CSS instead
3. Use IDs instead of CSS classes (it's just advice to use classes instead of IDs)
4. Reinitialize custom scrollbar each time window is resized (there is no need)

Think about different page structure - header/content/footer, where content occupies all available space, and all content children elements (with classes, not IDs!) are scrollable and use 100% height of parent container. All of this can be done using pure CSS without JS. And then apply custom scrollbar to your content children elements only once, no need to handle window resize.

**Comment by stephanlenhart** [comment]
Thanks for your answer! You are right, I'm not really proud of the current HTML page structure. That's why I also worked on a newer and better one (without JS usage). But here I ran into the problem that the jQuery scrollbar wasn't shown:

[Fiddle](https://fiddle.jshell.net/deb_ugger/temo6yd6/)

**Comment by gromo** [comment]
https://fiddle.jshell.net/temo6yd6/2/

add to CSS: `.scrollbar-dynamic { height: 100%; overflow: auto; }`

**Comment by stephanlenhart** [comment]
Awesome! Thanks, thats exactly what I tried to do!
